---
include:
  - project: 'pipeline-components/org/config'
    ref: master
    file: pipeline.yml

test amd64:
  variables:
    BUILD_ARCH: amd64
  extends: .test
  script:
    - docker run --rm "${CI_REGISTRY_IMAGE}/${BUILD_ARCH}:${CI_COMMIT_SHA}"  phpcs --version
