---
include:
  - project: 'pipeline-components/org/config'
    ref: v2.0.0
    file: pipeline.yml

test amd64:
  variables:
    BUILD_ARCH: amd64
  extends: .test
  script:
    - docker run --rm "${CI_REGISTRY_IMAGE}/build:${BUILD_ARCH}-${CI_COMMIT_SHA}"  phpcs --version

test amd64 defaultcmd:
  variables:
    BUILD_ARCH: amd64
  extends: .test
  script:
    - docker run --rm "${CI_REGISTRY_IMAGE}/build:${BUILD_ARCH}-${CI_COMMIT_SHA}"  --version
